jobs: detect if citool was run, restart if not
We seen in the wild that citool was not even executed,
this is a dead simple check to see if it was even executed
by looking if the debug log file is present.

If not, exit with 1 and let Nomad restart the job.

Resolves TFT-1721

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

diff --git a/ranch/public/jobs/tf-tmt b/ranch/public/jobs/tf-tmt
--- a/ranch/public/jobs/tf-tmt
+++ b/ranch/public/jobs/tf-tmt
@@ -118,6 +118,12 @@ citool-container.sh hide-secrets \
                     test-schedule-runner \
                     test-schedule-report
 
+# TFT-1721 - citool was not executed, exit non-zero to retry via Nomad
+if [ ! -e "citool-debug.txt" ]; then
+    echo -e "\033[31mError: citool was not run, request will be restarted!\033[0m" 1>&2
+    exit 1
+fi
+
 # skip archivation
 [ -n "$NO_ARCHIVE" ] && exit
 
